package sun.security.tools.keytool.resources;

import java.util.ListResourceBundle;

public final class keytool extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { ".Empty.value.", "(Empty value)" },
            { ".OPTION.", " [OPTION]..." },
            { ".PATTERN.printX509Cert.with.weak", "Owner: {0}\nIssuer: {1}\nSerial number: {2}\nValid from: {3} until: {4}\nCertificate fingerprints:\n\t SHA1: {5}\n\t SHA256: {6}\nSignature algorithm name: {7}\nSubject Public Key Algorithm: {8}\nVersion: {9}" },
            { ".RETURN.if.same.as.for.otherAlias.", "\t(RETURN if same as for <{0}>)" },
            { ".RETURN.if.same.as.keystore.password.", "\t(RETURN if same as keystore password):  " },
            { ".Storing.ksfname.", "[Storing {0}]" },
            { ".The.integrity.of.the.information.stored.in.the.srckeystore.", "* The integrity of the information stored in the srckeystore*\n* has NOT been verified!  In order to verify its integrity, *\n* you must provide the srckeystore password.                *" },
            { ".The.integrity.of.the.information.stored.in.your.keystore.", "* The integrity of the information stored in your keystore  *\n* has NOT been verified!  In order to verify its integrity, *\n* you must provide your keystore password.                  *" },
            { ".WARNING.WARNING.WARNING.", "*****************  WARNING WARNING WARNING  *****************" },
            { ".defaultValue.", "  [{0}]:  " },
            { ".is.not.trusted.", "... is not trusted. " },
            { ".keypass.and.new.can.not.be.specified.if.storetype.is.{0}", "-keypass and -new can not be specified if -storetype is {0}" },
            { ".keypasswd.commands.not.supported.if.storetype.is.PKCS12", "-keypasswd commands not supported if -storetype is PKCS12" },
            { ".keystore.must.be.NONE.if.storetype.is.{0}", "-keystore must be NONE if -storetype is {0}" },
            { ".storepasswd.and.keypasswd.commands.not.supported.if.storetype.is.{0}", "-storepasswd and -keypasswd commands not supported if -storetype is {0}" },
            { "Alias.alias.does.not.exist", "Alias <{0}> does not exist" },
            { "Alias.alias.has.no.certificate", "Alias <{0}> has no certificate" },
            { "Alias.alias.has.no.key", "Alias <{0}> has no key" },
            { "Alias.alias.references.an.entry.type.that.is.not.a.private.key.entry.The.keyclone.command.only.supports.cloning.of.private.key", "Alias <{0}> references an entry type that is not a private key entry.  The -keyclone command only supports cloning of private key entries" },
            { "Alias.name.alias", "Alias name: {0}" },
            { "Cannot.derive.signature.algorithm", "Cannot derive signature algorithm" },
            { "Cannot.find.environment.variable.", "Cannot find environment variable: " },
            { "Cannot.find.file.", "Cannot find file: " },
            { "Certificate.already.exists.in.keystore.under.alias.trustalias.", "Certificate already exists in keystore under alias <{0}>" },
            { "Certificate.already.exists.in.system.wide.CA.keystore.under.alias.trustalias.", "Certificate already exists in system-wide CA keystore under alias <{0}>" },
            { "Certificate.chain.length.", "Certificate chain length: " },
            { "Certificate.d.", "Certificate #%d:" },
            { "Certificate.fingerprint.SHA.256.", "Certificate fingerprint (SHA-256): " },
            { "Certificate.i.1.", "Certificate[{0,number,integer}]:" },
            { "Certificate.not.imported.alias.alias.already.exists", "Certificate not imported, alias <{0}> already exists" },
            { "Certificate.owner.", "Certificate owner: " },
            { "Certificate.reply.and.certificate.in.keystore.are.identical", "Certificate reply and certificate in keystore are identical" },
            { "Certificate.reply.does.not.contain.public.key.for.alias.", "Certificate reply does not contain public key for <{0}>" },
            { "Certificate.reply.was.installed.in.keystore", "Certificate reply was installed in keystore" },
            { "Certificate.reply.was.not.installed.in.keystore", "Certificate reply was not installed in keystore" },
            { "Certificate.stored.in.file.filename.", "Certificate stored in file <{0}>" },
            { "Certificate.was.added.to.keystore", "Certificate was added to keystore" },
            { "Certificate.was.not.added.to.keystore", "Certificate was not added to keystore" },
            { "Certification.request.stored.in.file.filename.", "Certification request stored in file <{0}>" },
            { "Changes.an.entry.s.alias", "Changes an entry's alias" },
            { "Changes.the.key.password.of.an.entry", "Changes the key password of an entry" },
            { "Changes.the.store.password.of.a.keystore", "Changes the store password of a keystore" },
            { "Clones.a.key.entry", "Clones a key entry" },
            { "Command.option.flag.needs.an.argument.", "Command option {0} needs an argument." },
            { "Commands.", "Commands:" },
            { "Creation.date.keyStore.getCreationDate.alias.", "Creation date: {0,date}" },
            { "Deletes.an.entry", "Deletes an entry" },
            { "Destination.alias.dest.already.exists", "Destination alias <{0}> already exists" },
            { "Do.you.still.want.to.add.it.no.", "Do you still want to add it? [no]:  " },
            { "Do.you.still.want.to.add.it.to.your.own.keystore.no.", "Do you still want to add it to your own keystore? [no]:  " },
            { "Empty.input", "Empty input" },
            { "Enter.alias.name.", "Enter alias name:  " },
            { "Enter.destination.keystore.password.", "Enter destination keystore password:  " },
            { "Enter.key.password.for.alias.", "Enter key password for <{0}>" },
            { "Enter.keystore.password.", "Enter keystore password:  " },
            { "Enter.new.alias.name.RETURN.to.cancel.import.for.this.entry.", "Enter new alias name\t(RETURN to cancel import for this entry):  " },
            { "Enter.prompt.alias.name.", "Enter {0} alias name:  " },
            { "Enter.source.keystore.password.", "Enter source keystore password:  " },
            { "Enter.the.password.to.be.stored.", "Enter the password to be stored:  " },
            { "Entry.for.alias.alias.not.imported.", "Entry for alias {0} not imported." },
            { "Entry.for.alias.alias.successfully.imported.", "Entry for alias {0} successfully imported." },
            { "Entry.type.type.", "Entry type: {0}" },
            { "Existing.entry.alias.alias.exists.overwrite.no.", "Existing entry alias {0} exists, overwrite? [no]:  " },
            { "Exports.certificate", "Exports certificate" },
            { "Extension.Request.", "Extension Request:" },
            { "Extensions.", "Extensions: " },
            { "Failed.to.establish.chain.from.reply", "Failed to establish chain from reply" },
            { "Failed.to.parse.input", "Failed to parse input" },
            { "Generated.keyAlgName.secret.key", "Generated {0} secret key" },
            { "Generated.keysize.bit.keyAlgName.secret.key", "Generated {0}-bit {1} secret key" },
            { "Generates.CRL", "Generates CRL" },
            { "Generates.a.certificate.request", "Generates a certificate request" },
            { "Generates.a.key.pair", "Generates a key pair" },
            { "Generates.a.secret.key", "Generates a secret key" },
            { "Generates.a.self.signed.certificate", "Generates a self-signed certificate" },
            { "Generates.certificate.from.a.certificate.request", "Generates certificate from a certificate request" },
            { "Generating.full.keyAlgName.key.pair.and.a.certificate.sigAlgName.issued.by.signerAlias.with.a.validity.of.days.for", "Generating {0} key pair and a certificate ({1}) issued by <{2}> with a validity of {3} days\n\tfor: {4}" },
            { "Generating.full.keyAlgName.key.pair.and.self.signed.certificate.sigAlgName.with.a.validity.of.days.for", "Generating {0} key pair and self-signed certificate ({1}) with a validity of {2} days\n\tfor: {3}" },
            { "Illegal.option.", "Illegal option:  " },
            { "Illegal.startdate.value", "Illegal startdate value" },
            { "Illegal.value.", "Illegal value: " },
            { "Import.command.completed.ok.entries.successfully.imported.fail.entries.failed.or.cancelled", "Import command completed:  {0} entries successfully imported, {1} entries failed or cancelled" },
            { "Imports.a.certificate.or.a.certificate.chain", "Imports a certificate or a certificate chain" },
            { "Imports.a.password", "Imports a password" },
            { "Imports.entries.from.a.JDK.1.1.x.style.identity.database", "Imports entries from a JDK 1.1.x-style identity database" },
            { "Imports.one.or.all.entries.from.another.keystore", "Imports one or all entries from another keystore" },
            { "Incomplete.certificate.chain.in.reply", "Incomplete certificate chain in reply" },
            { "Input.not.an.X.509.certificate", "Input not an X.509 certificate" },
            { "Install.reply.anyway.no.", "Install reply anyway? [no]:  " },
            { "Is.name.correct.", "Is {0} correct?" },
            { "Key.and.Certificate.Management.Tool", "Key and Certificate Management Tool" },
            { "Key.pair.not.generated.alias.alias.already.exists", "Key pair not generated, alias <{0}> already exists" },
            { "Key.password.is.too.short.must.be.at.least.6.characters", "Key password is too short - must be at least 6 characters" },
            { "Key.password.must.be.at.least.6.characters", "Key password must be at least 6 characters" },
            { "Keystore.file.does.not.exist.", "Keystore file does not exist: " },
            { "Keystore.file.exists.but.is.empty.", "Keystore file exists, but is empty: " },
            { "Keystore.password.is.too.short.must.be.at.least.6.characters", "Keystore password is too short - must be at least 6 characters" },
            { "Keystore.password.must.be.at.least.6.characters", "Keystore password must be at least 6 characters" },
            { "Keystore.provider.", "Keystore provider: " },
            { "Keystore.type.", "Keystore type: " },
            { "Lists.entries.in.a.keystore", "Lists entries in a keystore" },
            { "Must.not.specify.both.v.and.rfc.with.list.command", "Must not specify both -v and -rfc with 'list' command" },
            { "Must.specify.alias", "Must specify alias" },
            { "Must.specify.destination.alias", "Must specify destination alias" },
            { "NEWLINE", "\n" },
            { "New.certificate.self.signed.", "New certificate (self-signed):" },
            { "New.password.must.be.at.least.6.characters", "New password must be at least 6 characters" },
            { "New.prompt.", "New {0}: " },
            { "No.certificate.from.the.SSL.server", "No certificate from the SSL server" },
            { "No.entries.from.identity.database.added", "No entries from identity database added" },
            { "Not.X.509.certificate", "Not X.509 certificate" },
            { "Not.a.signed.jar.file", "Not a signed jar file" },
            { "Odd.number.of.hex.digits.found.", "Odd number of hex digits found: " },
            { "Options.", "Options:" },
            { "PKCS.10.with.weak", "PKCS #10 Certificate Request (Version 1.0)\nSubject: %1$s\nFormat: %2$s\nPublic Key: %3$s\nSignature algorithm: %4$s\n" },
            { "Password.is.too.short.must.be.at.least.6.characters", "Password is too short - must be at least 6 characters" },
            { "Passwords.must.differ", "Passwords must differ" },
            { "Please.provide.keysize.for.secret.key.generation", "Please provide -keysize for secret key generation" },
            { "Please.specify.srckeystore", "Please specify -srckeystore" },
            { "Prints.the.content.of.a.CRL.file", "Prints the content of a CRL file" },
            { "Prints.the.content.of.a.certificate", "Prints the content of a certificate" },
            { "Prints.the.content.of.a.certificate.request", "Prints the content of a certificate request" },
            { "Prints.the.program.version", "Prints the program version" },
            { "Problem.importing.entry.for.alias.alias.exception.Entry.for.alias.alias.not.imported.", "Problem importing entry for alias {0}: {1}.\nEntry for alias {0} not imported." },
            { "Public.keys.in.reply.and.keystore.don.t.match", "Public keys in reply and keystore don't match" },
            { "Re.enter.new.password.", "Re-enter new password: " },
            { "Re.enter.new.prompt.", "Re-enter new {0}: " },
            { "Re.enter.password.", "Re-enter password: " },
            { "Reply.has.no.certificates", "Reply has no certificates" },
            { "SSL.server.host.and.port", "SSL server host and port" },
            { "STAR", "*******************************************" },
            { "STARNN", "*******************************************\n\n" },
            { "Secret.key.not.generated.alias.alias.already.exists", "Secret Key not generated, alias <{0}> already exists" },
            { "Serial.ID.of.cert.to.revoke", "Serial ID of cert to revoke" },
            { "Signer.d.", "Signer #%d:" },
            { "Source.keystore.file.exists.but.is.empty.", "Source keystore file exists, but is empty: " },
            { "Submit.this.to.your.CA", "Submit this to your CA" },
            { "The.destination.pkcs12.keystore.has.different.storepass.and.keypass.Please.retry.with.destkeypass.specified.", "The destination pkcs12 keystore has different storepass and keypass. Please retry with -destkeypass specified." },
            { "They.don.t.match.Try.again", "They don't match. Try again" },
            { "This.extension.cannot.be.marked.as.critical.", "This extension cannot be marked as critical. " },
            { "Timestamp.", "Timestamp:" },
            { "Too.many.failures.Key.entry.not.cloned", "Too many failures. Key entry not cloned" },
            { "Too.many.failures.key.not.added.to.keystore", "Too many failures - key not added to keystore" },
            { "Too.many.failures.try.later", "Too many failures - try later" },
            { "Too.many.retries.program.terminated", "Too many retries, program terminated" },
            { "Top.level.certificate.in.reply.", "Top-level certificate in reply:\n" },
            { "Trust.this.certificate.no.", "Trust this certificate? [no]:  " },
            { "Unable.to.parse.denyAfter.string.in.exception.message", "Unable to parse denyAfter date string in exception message" },
            { "Unknown.AccessDescription.type.", "Unknown AccessDescription type: " },
            { "Unknown.Entry.Type", "Unknown Entry Type" },
            { "Unknown.extendedkeyUsage.type.", "Unknown extendedkeyUsage type: " },
            { "Unknown.extension.type.", "Unknown extension type: " },
            { "Unknown.keyUsage.type.", "Unknown keyUsage type: " },
            { "Unknown.password.type.", "Unknown password type: " },
            { "Unrecognized.GeneralName.type.", "Unrecognized GeneralName type: " },
            { "Usage.error.no.command.provided", "Usage error: no command provided" },
            { "Use.keytool.command.name.help.for.usage.of.command.name", "Use \"keytool -command_name --help\" for usage of command_name.\nUse the -conf <url> option to specify a pre-configured options file." },
            { "Use.keytool.help.for.all.available.commands", "Use \"keytool -?, -h, or --help\" for this help message" },
            { "Validity.must.be.greater.than.zero", "Validity must be greater than zero" },
            { "Warning.Different.store.and.key.passwords.not.supported.for.PKCS12.KeyStores.Ignoring.user.specified.command.value.", "Warning:  Different store and key passwords not supported for PKCS12 KeyStores. Ignoring user-specified {0} value." },
            { "Warning.Overwriting.existing.alias.alias.in.destination.keystore", "Warning: Overwriting existing alias {0} in destination keystore" },
            { "What.is.the.name.of.your.City.or.Locality.", "What is the name of your City or Locality?" },
            { "What.is.the.name.of.your.State.or.Province.", "What is the name of your State or Province?" },
            { "What.is.the.name.of.your.organization.", "What is the name of your organization?" },
            { "What.is.the.name.of.your.organizational.unit.", "What is the name of your organizational unit?" },
            { "What.is.the.two.letter.country.code.for.this.unit.", "What is the two-letter country code for this unit?" },
            { "What.is.your.first.and.last.name.", "What is your first and last name?" },
            { "Wrong.answer.try.again", "Wrong answer, try again" },
            { "X.509.extension", "X.509 extension" },
            { "Your.keystore.contains.keyStore.size.entries", "Your keystore contains {0,number,integer} entries" },
            { "Your.keystore.contains.keyStore.size.entry", "Your keystore contains {0,number,integer} entry" },
            { "access.the.cacerts.keystore", "access the cacerts keystore" },
            { "addprovider.option", "add security provider by name (e.g. SunPKCS11)\nconfigure argument for -addprovider" },
            { "alias.", "{0}, " },
            { "alias.has.no.X.509.certificate", "{0} has no X.509 certificate" },
            { "alias.has.no.public.key", "{0} has no public key" },
            { "alias.has.no.public.key.certificate.", "{0} has no public key (certificate)" },
            { "alias.in.cacerts", "Issuer <%s> in cacerts" },
            { "alias.in.keystore", "Issuer <%s>" },
            { "alias.keyStore.getCreationDate.alias.", "{0}, {1,date}, " },
            { "alias.name.of.the.entry.to.process", "alias name of the entry to process" },
            { "backup.keystore.warning", "The original keystore \"%1$s\" is backed up as \"%3$s\"..." },
            { "certificate.validity.start.date.time", "certificate validity start date/time" },
            { "command.{0}.is.ambiguous.", "command {0} is ambiguous:" },
            { "deprecate.keysize.for.ec", "Specifying -keysize for generating EC keys is deprecated, please use \"-groupname %s\" instead." },
            { "destination.alias", "destination alias" },
            { "destination.key.password", "destination key password" },
            { "destination.keystore.name", "destination keystore name" },
            { "destination.keystore.password", "destination keystore password" },
            { "destination.keystore.password.protected", "destination keystore password protected" },
            { "destination.keystore.provider.name", "destination keystore provider name" },
            { "destination.keystore.type", "destination keystore type" },
            { "distinguished.name", "distinguished name" },
            { "do.not.prompt", "do not prompt" },
            { "enter.dname.components", "Enter the distinguished name. Provide a single dot (.) to leave a sub-component empty or press ENTER to use the default value in braces." },
            { "groupname.keysize.coexist", "Cannot specify both -groupname and -keysize" },
            { "groupname.option.help", "Group name. For example, an Elliptic Curve name." },
            { "if.alias.not.specified.destalias.and.srckeypass.must.not.be.specified", "if alias not specified, destalias and srckeypass must not be specified" },
            { "if.keystore.is.not.password.protected.then.storepass.keypass.and.new.must.not.be.specified", "if keystore is not password protected, then -storepass, -keypass, and -new must not be specified" },
            { "if.protected.is.specified.then.storepass.keypass.and.new.must.not.be.specified", "if -protected is specified, then -storepass, -keypass, and -new must not be specified" },
            { "if.source.keystore.is.not.password.protected.then.srcstorepass.and.srckeypass.must.not.be.specified", "if source keystore is not password protected, then -srcstorepass and -srckeypass must not be specified" },
            { "if.srcprotected.is.specified.then.srcstorepass.and.srckeypass.must.not.be.specified", "if -srcprotected is specified, then -srcstorepass and -srckeypass must not be specified" },
            { "importing.keystore.status", "Importing keystore %1$s to %2$s..." },
            { "input.file.name", "input file name" },
            { "jks.storetype.warning", "The %1$s keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using \"keytool -importkeystore -srckeystore %2$s -destkeystore %2$s -deststoretype pkcs12\"." },
            { "key.algorithm.name", "key algorithm name" },
            { "key.algorithm.weak", "%1$s uses the %2$s algorithm which is considered a security risk." },
            { "key.bit", "%s key" },
            { "key.bit.disabled", "%s key (disabled)" },
            { "key.bit.size", "key bit size" },
            { "key.bit.weak", "%s key (weak)" },
            { "key.password", "key password" },
            { "key.password.for.alias.", "key password for <{0}>" },
            { "key.size.weak", "%1$s uses a %2$s which is considered a security risk." },
            { "keyalg.option.missing.error", "The -keyalg option must be specified." },
            { "keystore.name", "keystore name" },
            { "keystore.password", "keystore password" },
            { "keystore.type", "keystore type" },
            { "keytool.error.", "keytool error: " },
            { "migrate.keystore.warning", "Migrated \"%1$s\" to %4$s. The %2$s keystore is backed up as \"%3$s\"." },
            { "multiple.commands.1.2", "Only one command is allowed: both %1$s and %2$s were specified." },
            { "n", "n" },
            { "new.password", "new password" },
            { "no", "no" },
            { "no.field.in.dname", "At least one field must be provided. Enter again." },
            { "one.in.many", "%1$s #%2$d of %3$d" },
            { "one.in.many1", "%1$s #%2$d" },
            { "one.in.many2", "%1$s of signer #%2$d" },
            { "one.in.many3", "%1$s #%2$d of signer #%3$d" },
            { "option.1.set.twice", "The %s option is specified multiple times. All except the last one will be ignored." },
            { "output.file.name", "output file name" },
            { "output.in.RFC.style", "output in RFC style" },
            { "password.through.protected.mechanism", "password through protected mechanism" },
            { "provclass.not.a.provider", "%s not a provider" },
            { "provider.class.not.found", "Provider \"%s\" not found" },
            { "provider.class.option", "add security provider by fully-qualified class name\nconfigure argument for -providerclass" },
            { "provider.classpath", "provider classpath" },
            { "provider.name", "provider name" },
            { "provider.name.not.found", "Provider named \"%s\" not found" },
            { "reply", "Reply" },
            { "showinfo.command.help", "Displays security-related information" },
            { "showinfo.no.option", "Missing option for -showinfo. Try \"keytool -showinfo -tls\"." },
            { "signature.algorithm.name", "signature algorithm name" },
            { "signed.jar.file", "signed jar file" },
            { "signer.alias", "signer alias" },
            { "signer.key.password", "signer key password" },
            { "size.bit.alg", "%1$d-bit %2$s" },
            { "source.alias", "source alias" },
            { "source.key.password", "source key password" },
            { "source.keystore.name", "source keystore name" },
            { "source.keystore.password", "source keystore password" },
            { "source.keystore.password.protected", "source keystore password protected" },
            { "source.keystore.provider.name", "source keystore provider name" },
            { "source.keystore.type", "source keystore type" },
            { "the.certificate", "The certificate" },
            { "the.certificate.request", "The certificate request" },
            { "the.crl", "The CRL" },
            { "the.generated.certificate", "The generated certificate" },
            { "the.generated.certificate.request", "The generated certificate request" },
            { "the.generated.crl", "The generated CRL" },
            { "the.generated.secretkey", "The generated secret key" },
            { "the.input", "The input" },
            { "the.issuer", "The issuer" },
            { "the.keystore.or.storetype.option.cannot.be.used.with.the.cacerts.option", "The -keystore or -storetype option cannot be used with the -cacerts option" },
            { "the.tsa.certificate", "The TSA certificate" },
            { "tls.option.help", "Displays TLS configuration information" },
            { "trust.certificates.from.cacerts", "trust certificates from cacerts" },
            { "validity.number.of.days", "validity number of days" },
            { "verbose.output", "verbose output" },
            { "verified.by.s.in.s.weak", "Verified by %1$s in %2$s with a %3$s" },
            { "warning.cacerts.option", "Warning: use -cacerts option to access cacerts keystore" },
            { "warning.not.verified.make.sure.keystore.is.correct", "WARNING: not verified. Make sure -keystore is correct." },
            { "warning.not.verified.make.sure.keystore.is.correct.or.specify.trustcacerts", "WARNING: not verified. Make sure -keystore is correct or specify -trustcacerts." },
            { "whose.key.disabled", "%1$s uses a %2$s which is considered a security risk and is disabled." },
            { "whose.key.weak", "%1$s uses a %2$s which is considered a security risk. It will be disabled in a future update." },
            { "whose.sigalg.disabled", "%1$s uses the %2$s signature algorithm which is considered a security risk and is disabled." },
            { "whose.sigalg.usagesignedjar", "%1$s uses the %2$s signature algorithm which is considered a security risk and cannot be used to sign JARs after %3$s." },
            { "whose.sigalg.weak", "%1$s uses the %2$s signature algorithm which is considered a security risk." },
            { "with.disabled", "%s (disabled)" },
            { "with.weak", "%s (weak)" },
            { "y", "y" },
            { "yes", "yes" },
        };
    }
}
